name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@v3041bf56c941b39c61721a86cd11f3bb1338122a

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: go build
